In [1]:
from pathlib import Path
import sys

sys.path.insert(0, str(Path.cwd().parent))

from apis import ticketmaster as tm

In [2]:
import apis.events.client_models.ticketmaster_event_model as em
import apis.events.event_record as er
import apis.events.events_mapper as ema

In [5]:
from data_processor.ticketmaster.events_processor import EventsProcessor

endpoint = "/events.json"
embedded_parts = [("_embedded", "events")]
kword_filters_gb= {"keyword":"festival", "countryCode":"GB"}
kword_filters_uk= {"keyword":"festival", "countryCode":"UK"}
events_list = []

response_data_gb = tm.get_ticketmaster_data(endpoint, embedded_parts, filters=kword_filters_gb)
response_data_uk = tm.get_ticketmaster_data(endpoint, embedded_parts, filters=kword_filters_uk)
events_list = response_data_gb + response_data_uk

Status Code: 200
URL Used: https://app.ticketmaster.com/discovery/v2/events.json?apikey=TGzUiTz6ZRVqDBPAJftmo0CRJNLxmxOQ&size=200&keyword=festival&countryCode=GB
Status Code: 200
URL Used: https://app.ticketmaster.com/discovery/v2/events.json?apikey=TGzUiTz6ZRVqDBPAJftmo0CRJNLxmxOQ&size=200&keyword=festival&countryCode=UK

In [9]:
events_models, invalid_models = EventsProcessor.validate_events(events_list)
events_df = EventsProcessor.build_events_dataframe(events_models)

In [10]:
events_df.head()

,name,typeOfEvent,id,url,locale,startDate,multipleDays,venues,genre_name,subgenre_name
0,Reading Festival 2026 - Friday,event,1AdjZbVGklbLnsr,https://www.ticketmaster.co.uk/reading-festiva...,en-us,2026-08-28,False,[/discovery/v2/venues/KovZ9177Bn7?locale=en-us],Undefined,Undefined
1,Leeds Festival 2026 - Saturday,event,1AdfZbVGklFrtT2,https://www.ticketmaster.co.uk/leeds-festival-...,en-us,2026-08-29,False,[/discovery/v2/venues/KovZ9177JYV?locale=en-us],Undefined,Undefined
2,Counterfeit Festival,event,G5dzZ_aLlekuL,https://www.ticketmaster.co.uk/counterfeit-fes...,en-us,2026-08-22,False,[/discovery/v2/venues/KovZ9177AAV?locale=en-us],Hip-Hop/Rap,Trap
3,Uprising Festival,event,LvZ18QxOrVvn588vO4Ui0,https://www.universe.com/events/uprising-festi...,en-us,2027-04-10,False,[/discovery/v2/venues/KovZ9177jUf?locale=en-us],Metal,Heavy Metal
4,Sandringham Heritage Live Festival - 5 Day Ticket,event,17u8v0G6ur4ptiu,https://www.ticketmaster.co.uk/sandringham-her...,en-us,2026-08-19,False,[/discovery/v2/venues/KovZ9177NaV?locale=en-us],Other,Other

In [11]:
from data_processor.ticketmaster.venues_processor import VenuesProcessor
endpoint = "/venues.json"
embedded_parts = [("_embedded", "venues")]
kword_filters_gb= {"countryCode":"GB"}
kword_filters_uk= {"countryCode":"UK"}
venues_list = []

response_data_gb = tm.get_ticketmaster_data(endpoint, embedded_parts, filters=kword_filters_gb)
response_data_uk = tm.get_ticketmaster_data(endpoint, embedded_parts, filters=kword_filters_uk)
venues_list = response_data_gb + response_data_uk

Status Code: 200
URL Used: https://app.ticketmaster.com/discovery/v2/venues.json?apikey=TGzUiTz6ZRVqDBPAJftmo0CRJNLxmxOQ&size=200&countryCode=GB
Status Code: 200
URL Used: https://app.ticketmaster.com/discovery/v2/venues.json?apikey=TGzUiTz6ZRVqDBPAJftmo0CRJNLxmxOQ&size=200&countryCode=UK

In [12]:
venues_models, invalid_models = EventsProcessor.validate_events(events_list)
venues_df = EventsProcessor.build_events_dataframe(venues_models)

In [14]:
venues_df.head()

,name,typeOfEvent,id,url,locale,startDate,multipleDays,venues,genre_name,subgenre_name
0,Reading Festival 2026 - Friday,event,1AdjZbVGklbLnsr,https://www.ticketmaster.co.uk/reading-festiva...,en-us,2026-08-28,False,[/discovery/v2/venues/KovZ9177Bn7?locale=en-us],Undefined,Undefined
1,Leeds Festival 2026 - Saturday,event,1AdfZbVGklFrtT2,https://www.ticketmaster.co.uk/leeds-festival-...,en-us,2026-08-29,False,[/discovery/v2/venues/KovZ9177JYV?locale=en-us],Undefined,Undefined
2,Counterfeit Festival,event,G5dzZ_aLlekuL,https://www.ticketmaster.co.uk/counterfeit-fes...,en-us,2026-08-22,False,[/discovery/v2/venues/KovZ9177AAV?locale=en-us],Hip-Hop/Rap,Trap
3,Uprising Festival,event,LvZ18QxOrVvn588vO4Ui0,https://www.universe.com/events/uprising-festi...,en-us,2027-04-10,False,[/discovery/v2/venues/KovZ9177jUf?locale=en-us],Metal,Heavy Metal
4,Sandringham Heritage Live Festival - 5 Day Ticket,event,17u8v0G6ur4ptiu,https://www.ticketmaster.co.uk/sandringham-her...,en-us,2026-08-19,False,[/discovery/v2/venues/KovZ9177NaV?locale=en-us],Other,Other